# Generated by Django 4.2.2 on 2023-07-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contentn',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(verbose_name='조회수'),
        ),
    ]
